{% set name = "climlab" %}
{% set version = "0.7.0" %}
{% set sha256 = "7c69a09033e0aa412707b620687ea0a04b2a1b03967a070ba1176db083c94af7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [(win and py2k) or (win32 and py3k)]
  number: 0

requirements:
  build:
    - toolchain
    - mingwpy  # [win and py2k]
    - flang  # [win and py3k]
    - gcc  # [osx]
    - python
    - setuptools
    - libgfortran  # [linux]
    - numpy 1.11.*  # [not (win and py3k)]
    - numpy 1.14.*  # [win and py3k]

  run:
    - python
    - numpy >=1.11  # [not (win and py3k)]
    - numpy >=1.14  # [win and py3k]
    - libflang  # [win and py3k]
    - scipy
    - netcdf4
    - xarray
    - libgfortran  # [linux or osx]
    - future
    - numba  # [py2k]

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab.tests

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
