{% set version = "0.7.10" %}

package:
  name: climlab
  version: {{ version }}

source:
  #path: /Users/br546577/code/climlab
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: 5ece1c2b7a28602c2c39c67a8ecd065054dfef49f2cb9c54548c153f2d2114bd

build:
  number: 3
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - flang  # [win and py3k]
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang  # [win and py3k]
    - scipy
    - pydap
    - requests
    - xarray
    - future
    - attrdict

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab  # [not osx]
    - pytest -v -m fast --pyargs climlab --ignore=test_emanuel_convection  # [osx]
    #  Note that we are skipping these particular tests on osx because of a
    #  mysterious failure on conda-forge
    #  that only shows up with certain combinations of numpy and python versions
    #  e.g. https://github.com/conda-forge/climlab-feedstock/pull/44
    #  I've manually verified that the builds pass all tests locally and behave normally

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
