{% set version = "0.7.1" %}

package:
  name: climlab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/climlab/climlab-{{ version }}.tar.gz
  sha256: 018318907614cc55b9e61858de3d78c010dd218b370457c7cde75bccaa186d39

build:
  skip: True  # [win32 or (win and py27)]
  number: 2

requirements:
  build:
     - {{ compiler('fortran') }}
     - {{ compiler('c') }}
  host:
    - flang  # [win and py3k]
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libflang  # [win and py3k]
    - scipy
    - xarray
    - future
    - attrdict
    - numba  # [py2k]

test:
  requires:
    - pytest
  imports:
    - climlab
  commands:
    - pytest -v -m fast --pyargs climlab.tests

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
