travis:
  secure:
    BINSTAR_TOKEN: L4Nr30hHGsBrbABWfiodB647DTfB/G6Tc9p0zAHdQaIPMsxMq9qjdV5c6KNb/dnZxKQesTadLdkADCJa5g9frzMVbrDkrORQ4kXguD134vSUbbwzL+7HTLoRsBKiLQJE1ndIrXzWgtSgy8Yd1ZHMquMcPC++44a/ko4inJ3LDLz8hLfItKI8H0+pUGrSuH6eiAGnxir4z9kPkaO50/tV+6Mp2r5Ej51JQ5MJKlCqA53YByjxjNcebW28wWNvLOgbzh3HqZ0lLEUiwqe92DZgknQ83UoLFnTCwSEXvBaCk8OolVjicf+K+vRwnzWkb4hrQaTk9/CBTKDcg4Hljq7S44Q6wG9gWApMm+z5xRsTed2o2PcDYc30RKT4vmu4is5K3VCSjKj9dTFuihZVBq0oxX1gq5EKYEJEn9Lmaqvsjiyv9efPOMmQtF5FB5N2HC9DhBqTBsz/Ova1OaBsVdv7ljGSHYqvV45r+75DAXZSiaATvMXF9JDaiRXPTQpO1qy6jFRvI43r3+ku6CGZM9OhSlgZZRcXCMi3Pmh0saaYUvrmHNVqJEPCJyuprkDT+/QroeYJ7/0FjfE9s5GBhovDGP52P2QSKfQuOiPQfUjKLMuLMFV9nF67BAeknl1UpN8g0UMJtUjE8hneaQB/y9Y2Ho5+kRbx1xYxApwXw1gC63c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: appveyor
